version: '3.8'

services:
  api:
    build: .
    container_name: sentinel_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./results.json:/app/results.json
      - ./configs:/app/configs
    environment:
      - PYTHONPATH=/app

  frontend:
    build: .
    container_name: sentinel_frontend
    command: streamlit run app/frontend.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
    depends_on:
      - api
    environment:
      - BACKEND_URL=http://api:8000/predict
      - PYTHONPATH=/app
